Update the Calendar API to get only upcoming Onelives
sef-global/sef-data-holder pull request #20
Opened 2020-03-26 19:21 UTC by Piumal1999

## Purpose

The purpose of this PR is to fix #19 

## Goals

Update the Calendar API to get only the upcoming Onelives

## Approach

Got the current time and formatted it to the RFC3339 date/time format which is used in google APIs.
Added the "timeMin" filter to get only the upcoming events.

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Related PRs
 
N/A

## Test environment
 
Ubuntu 19.04
OpenJDK version 11.0.5

## Learning

N/A

2020-03-26 19:23 UTC, Piumal1999 commented
@jayasanka-sack,
For which sites do we have to allow CORS?

2020-03-27 12:13 UTC, jayasanka-sack commented
> @jayasanka-sack,
> For which sites do we have to allow CORS?

Let's allow all for now

2020-03-27 12:29 UTC, jayasanka-sack requested changes
Good job @Piumal1999 !

Please fix the following formatting issues. :)

2020-03-27 12:29 UTC, jayasanka-sack commented on src/main/java/org/sefgobal/dataholder/api/CalendarAPI.java
Remove the extra space

2020-03-27 12:29 UTC, jayasanka-sack commented on src/main/java/org/sefgobal/dataholder/api/CalendarAPI.java
> +
Remove the extra space

2020-03-27 12:29 UTC, jayasanka-sack commented on src/main/java/org/sefgobal/dataholder/api/CalendarAPI.java
Remove the extra space

2020-03-27 12:29 UTC, jayasanka-sack commented on src/main/java/org/sefgobal/dataholder/api/CalendarAPI.java
> +
Remove the extra space

2020-03-27 12:29 UTC, jayasanka-sack commented on src/main/java/org/sefgobal/dataholder/api/CalendarAPI.java
> +                "/events?timeMin=" + formattedDateTime + "&key=" + googleApiKey;
```
String url = "https://www.googleapis.com/calendar/v3/calendars/" +
                oneliveCalendarId +
                "/events?timeMin=" +
                formattedDateTime +
                "&key=" +
                googleApiKey;
```

2020-03-27 17:35 UTC, Piumal1999 commented
Fixed the formatting issues

2020-03-28 08:03 UTC, jayasanka-sack commented on src/main/java/org/sefgobal/dataholder/api/CalendarAPI.java
> +
Check these too

2020-03-28 08:04 UTC, jayasanka-sack commented
@Piumal1999 Remove unnecessary white spaces

2020-03-28 15:25 UTC, Piumal1999 commented
> @Piumal1999 Remove unnecessary white spaces

Done

2020-03-30 04:48 UTC, jayasanka-sack approved these changes
Good job!

2020-03-30 04:48 UTC, merged