Set Content Type of payloads to application/json
sef-global/sef-data-holder pull request #21
Opened 2020-03-28 07:52 UTC by yohanym95

## Purpose

The purpose of this PR is to fix #14 

## Goals

Currently, the payloads sent as plain strings. need to  get them as JSON.

## Approach

Set ContentType of payloads to application/json

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Related PRs
 

## Test environment

Windows 10
Google chrome 

## Learning

https://www.codota.com/code/java/methods/javax.servlet.http.HttpServletResponse/setContentType

2020-03-28 08:00 UTC, jayasanka-sack commented on src/main/java/org/sefgobal/dataholder/api/CalendarAPI.java
> +import org.springframework.http.MediaType;
Are we need this import?

2020-03-28 08:00 UTC, jayasanka-sack commented on src/main/java/org/sefgobal/dataholder/api/YoutubeAPI.java
> +import javax.servlet.http.HttpServletResponseWrapper;
Are we need this import?

2020-03-28 08:01 UTC, jayasanka-sack requested changes
Good job @yohanym95 

Remove unnecessary formattings.

2020-03-28 08:01 UTC, jayasanka-sack commented
Did you test this implementation?

2020-03-28 08:42 UTC, yohanym95 commented on src/main/java/org/sefgobal/dataholder/api/YoutubeAPI.java
> +import javax.servlet.http.HttpServletResponseWrapper;
No, i will remove them.

2020-03-28 08:45 UTC, yohanym95 commented
Yes Jayasanka, I tested it by using postman.

2020-03-28 13:49 UTC, anjula-sack requested changes
Keep only `response.setContentType("application/json");` and remove unwanted imports only. Do not format unwanted files like pom.xml

2020-03-28 19:05 UTC, yohanym95 commented
@anjula-sack i removed unwanted imports.

2020-03-29 02:27 UTC, anjula-sack requested changes
Remove unwanted spaces you added in those three files. Do not format unwanted files like pom.xml .

2020-03-30 05:38 UTC, jayasanka-sack requested changes
Remove unnecessary new lines.

Also, it would be nice if u could attach a GIF of a screen recording. (postman)

2020-03-30 06:51 UTC, yohanym95 commented
![sefDataHolder](https://user-images.githubusercontent.com/31344335/77882979-cc2aee00-727f-11ea-9cbf-ef644a6d4cca.gif)

I attached  GIF file of screen recording and removed unnecessary new lines.

2020-03-30 10:37 UTC, Piumal1999 commented
@yohanmy95 There are some conflicts in the YoutubeAPI file.

2020-03-30 12:13 UTC, anjula-sack commented on src/main/java/org/sefgobal/dataholder/api/YoutubeAPI.java
> +
Remove this space.

2020-03-30 12:13 UTC, anjula-sack commented on src/main/java/org/sefgobal/dataholder/api/YoutubeAPI.java
remove spaces in here too.

2020-03-30 12:16 UTC, anjula-sack commented on src/main/java/org/sefgobal/dataholder/api/CalendarAPI.java
> +
Remove this space too

2020-03-30 12:16 UTC, anjula-sack requested changes
@yohanym95  I added some comments

2020-03-30 12:53 UTC, yohanym95 commented
@anjula-sack I removed unnecessary spaces.

2020-03-30 13:15 UTC, anjula-sack approved these changes
Awesome! @yohanym95

2020-03-30 14:02 UTC, jayasanka-sack approved these changes

2020-03-30 14:02 UTC, merged